import { v4 as uuidv4 } from "uuid";

// This is single card data in home page
export const card = [
  {
    id: uuidv4(),
    title: "Https",
    path: "/http",
    text: "The Hypertext Transfer Protocol (HTTP) is an application layer protocol in the Internet protocol suite model for distributed, collaborative, hypermedia information systems.",
  },
  {
    id: uuidv4(),
    title: "React",
    path: "/react",
    text: "A JavaScript library for building user interfaces. React stands at the intersection of design and programming. It lets you take a complex user interface, and break it down into nestable and reusable pieces called “components” that fit well together.",
  },
  {
    id: uuidv4(),
    title: "React Router",
    path: "/react-router",
    text: "React Router is a collection of React components, hooks and utilities that make it easy to build multi-page applications with React. This reference contains the function signatures and return types of the various interfaces in React Router.",
  },
  {
    id: uuidv4(),
    title: "Redux Toolkit",
    path: "/redux_toolkit",
    text: "Redux is a pattern and library for managing and updating application state, using events called 'actions'.",
  },
  {
    id: uuidv4(),
    title: "TypeScript",
    path: "/typescript",
    text: "TypeScript is a programming language developed and maintained by Microsoft. It is a strict syntactical superset of JavaScript and adds optional static typing to the language. ",
  },
  {
    id: uuidv4(),
    title: "JavaScript",
    path: "/javascript",
    text: "JavaScript (JS) is a lightweight, interpreted, or just-in-time compiled programming language with first-class functions.",
  },
  {
    id: uuidv4(),
    title: "Asynchronous JS",
    path: "/asynchronous_js",
    text: "The term asynchronous refers to two or more objects or events not existing or happening at the same time (or multiple related things happening without waiting for the previous one to complete).",
  },
  {
    id: uuidv4(),
    title: "CS",
    path: "/cs",
    text: "This page is about the common terms in computer science or computer programming languages.",
  },
  {
    id: uuidv4(),
    title: "OOP",
    path: "/oop",
    text: "Object-oriented programming (OOP) is a programming paradigm based on the concept of \"objects\", which can contain data and code.",
  },
  {
    id: uuidv4(),
    title: "Computer graphics",
    path: "/cg",
    text: "Computer graphics deals with generating images and art with the aid of computers.",
  },
  {
    id: uuidv4(),
    title: "Git",
    path: "/git",
    text: "Git is a free and open source distributed version control system designed to handle everything from small to very large projects with speed and efficiency.",
  },
  {
    id: uuidv4(),
    title: "Data Structure",
    path: "/data_structure",
    text: "Data Structures are the programmatic way of storing data so that data can be used efficiently.",
  },
  {
    id: uuidv4(),
    title: "Algorithms",
    path: "/algorithms",
    text: "Algorithm is a step-by-step procedure, which defines a set of instructions to be executed in a certain order to get the desired output.",
  },
  {
    id: uuidv4(),
    title: "Webpack",
    path: "/webpack",
    text: "Webpack is a static module bundler for modern JavaScript applications.",
  },
  {
    id: uuidv4(),
    title: "Web Components",
    path: "/web_components",
    text: "Web Components is a suite of different technologies allowing you to create reusable custom elements — with their functionality encapsulated away from the rest of your code — and utilize them in your web apps.",
  },
  {
    id: uuidv4(),
    title: "Web Terms",
    path: "/web_terms",
    text: "The World Wide Web (WWW), commonly known as the Web, is an information system where documents and other web resources are identified by Uniform Resource Locators (URLs, such as https://example.com/), which may be interlinked by hyperlinks, and are accessible over the Internet.",
  },
  {
    id: uuidv4(),
    title: "WebGL",
    path: "/webgl",
    text: "WebGL (Web Graphics Library) is the new standard for 3D graphics on the Web, designed for rendering 2D graphics and interactive 3D graphics.",
  },
  {
    id: uuidv4(),
    title: "Other Terms",
    path: "/other_terms",
    text: "Git is a free and open source distributed version control system designed to handle everything from small to very large projects with speed and efficiency.",
  },
  {
    id: uuidv4(),
    title: "Mathematics",
    path: "/math",
    text: "Mathematics is an area of knowledge that includes such topics as numbers (arithmetic and number theory), formulas and related structures (algebra), shapes and the spaces in which they are contained (geometry), and quantities and their changes (calculus and analysis).",
  },
  {
    id: uuidv4(),
    title: "Geometry",
    path: "/geometry",
    text: "Geometry is, with arithmetic, one of the oldest branches of mathematics. A mathematician who works in the field of geometry is called a geometer.",
  },
  {
    id: uuidv4(),
    title: "Calculus",
    path: "/calculus",
    text: "Calculus, originally called infinitesimal calculus or 'the calculus of infinitesimals', is the mathematical study of continuous change, in the same way that geometry is the study of shape, and algebra is the study of generalizations of arithmetic operations.",
  },
  {
    id: uuidv4(),
    title: "Algebra",
    path: "/algebra",
    text: "Algebra is the study of variables and the rules for manipulating these variables in formulas; it is a unifying thread of almost all of mathematics.",
  },
  {
    id: uuidv4(),
    title: "Mathematical analysis",
    path: "/math_analysis",
    text: "Analysis is the branch of mathematics dealing with continuous functions, limits, and related theories, such as differentiation, integration, measure, infinite sequences, series, and analytic functions.",
  },
  {
    id: uuidv4(),
    title: "Physics",
    path: "/physics",
    text: "Physics is the natural science that studies matter, its fundamental constituents, its motion and behavior through space and time, and the related entities of energy and force.",
  },
  {
    id: uuidv4(),
    title: "Logic",
    path: "/logic",
    text: "Logic is the study of correct reasoning or good arguments. It is often defined in a more narrow sense as the science of deductively valid inferences or of logical truths.",
  },
  {
    id: uuidv4(),
    title: "Linguisitics",
    path: "/linguistics",
    text: "Linguistics is the scientific study of human language. It entails a comprehensive, systematic, objective, and precise analysis of all aspects of language, particularly its nature and structure.",
  },
  {
    id: uuidv4(),
    title: "Philosophy",
    path: "/philosophy",
    text: "Philosophy (from Greek: φιλοσοφία, philosophia, 'love of wisdom') is the study of general and fundamental questions, such as those about existence, reason, knowledge, values, mind, and language. Such questions are often posed as problems to be studied or resolved.",
  },
  {
    id: uuidv4(),
    title: "Psychology",
    path: "/psychology",
    text: "Psychology is the scientific study of mind and behavior. Psychology includes the study of conscious and unconscious phenomena, including feelings and thoughts.",
  },
  {
    id: uuidv4(),
    title: "English",
    path: "/english",
    text: "English is a West Germanic language of the Indo-European language family, with its earliest forms spoken by the inhabitants of early medieval England.",
  },
  {
    id: uuidv4(),
    title: "Business",
    path: "/business",
    text: "Business is the practice of making one's living or making money by producing or buying and selling products (such as goods and services).[1][2][3][4] It is also 'any activity or enterprise entered into for profit.'",
  },
  {
    id: uuidv4(),
    title: "Note",
    path: "/note",
    text: "This page is about the notes that I have been thought and practiced in the programming",
  },
];
